from llm.openai_client import prompt_model
from rag import query_data, chunk_data, index_data

def main(viz_type, question, columns, summary_stats, collection):
    """
    Generate Python code for a visualization based on provided profiling parameters and examples 
    retrieved from a ChromaDB collection.

    The function first queries the collection for examples related to the data question and 
    then uses an LLM to generate Python code for building a visualization.

    Args:
        viz_type (str): The visualization type determined by the input profiler.
        question (str): The data question generated by the input profiler.
        columns (dict): A dictionary of column names and their data types.
        summary_stats (dict): Summary statistics of the dataset.
        collection (Collection): The ChromaDB collection to query for relevant examples.

    Returns:
        str: Generated Python code for creating the desired visualization.
    """
    # Retrieve examples from the collection based on the question
    examples = query_data(question, collection)
    # Generate Python code using the prompt_model (LLM)
    code_output = prompt_model(
        f"Generate python code for this visualization, given the following parameters:\n"
        f"- Visualization Type: {viz_type}\n"
        f"- Data Question: {question}\n"
        f"- Columns: {columns}\n"
        f"- Summary Statistics: {summary_stats}\n"
        f"Model your output on the following examples:\n{examples}"
    )
    return code_output

if __name__ == "__main__":
    # Example usage:
    # In a complete application these values would come from the input_profiler module.
    viz_type = "bar"
    question = "What is the distribution of film ratings?"
    columns = {"rating": "float", "title": "object"}
    summary_stats = {"rating": {"mean": 7.5, "std": 1.2}}

    # Build the collection using the RAG module
    annotations, _ = index_data()
    collection = chunk_data(annotations)
    
    generated_code = main(viz_type, question, columns, summary_stats, collection)
    print("Generated Code:")
    print(generated_code)